#%RAML 1.0 Trait

responses:
  400:
    body:
      application/json:
  
        type:  !include/datatyes/commonresponedatatype.raml
      
        example: !include/examples/error 400 respone file.json
            
  401:
    body:
      application/json:
        type: !include/datatyes/commonresponedatatype.raml
                
        example: !include/examples/error 401 responefile.json
         
  404:
    body:
      application/json:
        type: !include/datatyes/commonresponedatatype.raml
        example: !include/examples/error 404 respone file.json
         
  500:
    body:
      application/json:
        type: !include/datatyes/commonresponedatatype.raml
       
        example: !include/examples/error 500 respone file.json
         